import 'package:flutter_blue_plus/flutter_blue_plus.dart';
import 'dart:math';

const String ganitDangalServiceUuid = "0000aaaa-0000-1000-8000-00805f9b34fb";
const String ganitDangalSeedCharUuid = "0000bbbb-0000-1000-8000-00805f9b34fb";
const String ganitDangalScoreCharUuid = "0000cccc-0000-1000-8000-00805f9b34fb";

class DuelClientService {
  BluetoothDevice? targetDevice;
  BluetoothCharacteristic? seedChar;
  BluetoothCharacteristic? scoreChar;

  /// Scans for the specific Ganit Dangal host UUID
  Future<void> scanForHost() async {
    await FlutterBluePlus.startScan(
      withServices: [Guid(ganitDangalServiceUuid)],
      timeout: const Duration(seconds: 15),
    );

    FlutterBluePlus.scanResults.listen((results) {
      for (ScanResult r in results) {
        if (r.advertisementData.serviceUuids.contains(
          Guid(ganitDangalServiceUuid),
        )) {
          targetDevice = r.device;
          FlutterBluePlus.stopScan();
          _connectToHost();
          break;
        }
      }
    });
  }

  Future<void> _connectToHost() async {
    if (targetDevice == null) return;
    await targetDevice!.connect(autoConnect: false, license: License.nonprofit);
    List<BluetoothService> services = await targetDevice!.discoverServices();

    for (var service in services) {
      if (service.uuid == Guid(ganitDangalServiceUuid)) {
        for (var characteristic in service.characteristics) {
          if (characteristic.uuid == Guid(ganitDangalSeedCharUuid)) {
            seedChar = characteristic;
          } else if (characteristic.uuid == Guid(ganitDangalScoreCharUuid)) {
            scoreChar = characteristic;
            await scoreChar!.setNotifyValue(
              true,
            ); // Listen for opponent score updates
          }
        }
      }
    }
  }

  /// Reads the random 4-digit seed generated by the host
  Future<int?> readSeed() async {
    if (seedChar != null) {
      List<int> value = await seedChar!.read();
      if (value.isNotEmpty) {
        // Reconstruct integer from bytes
        return (value[0] << 8) | value[1];
      }
    }
    return null;
  }

  /// Sends a single-byte payload (0x01) to update live score
  Future<void> sendScoreUpdate(bool isCorrect) async {
    if (scoreChar != null && isCorrect) {
      await scoreChar!.write([0x01], withoutResponse: true);
    }
  }

  Stream<List<int>>? get opponentScoreStream => scoreChar?.lastValueStream;
}

class DuelHostService {
  int? currentSeed;

  /// Note: flutter_blue_plus natively acts as a Central (Client).
  /// True peripheral/advertising mode typically requires `flutter_ble_peripheral`.
  /// Below represents the architectural implementation required for the Host mode.
  Future<void> startHost() async {
    // 1. Generate 4-digit seed
    currentSeed = 1000 + Random().nextInt(9000);

    // 2. Setup GATT Server (Peripheral mode)
    // - Add Service UUID: ganitDangalServiceUuid
    // - Add Characteristic UUID: ganitDangalSeedCharUuid (Permissions: Read)
    // - Add Characteristic UUID: ganitDangalScoreCharUuid (Permissions: WriteWithoutResponse, Notify)

    // 3. Set the characteristic value for the seed
    // e.g. seedCharacteristic.setValue([currentSeed! >> 8, currentSeed! & 0xFF]);

    // 4. Start Advertising the service UUID so clients can discover
  }

  // Invoked when client writes 0x01 to the score characteristic
  void onOpponentScored() {
    // Dispatch score update to UI
  }
}
